#!/bin/bash
if [[ "$1" =~ ^ddc23[a-z][a-z](-.+)?.xml$ ]]; then
  set -x
  catmandu convert marcxml to ndjson \
	  --fix "add_field(language,${1:5:2})" --fix ddc2jskos.fix \
	  < $1 > ${1/.xml/.ndjson}
else
  echo "Usage: $0 ddc23XX.xml"
  exit 1
fi
