bc.concepts.ndjson:
	curl https://bartoc.org/api/data?uri=http://bartoc.org/en/node/20400 > bc.scheme.json
	jskos-convert Concept bc.concepts.csv -f csv -s bc.scheme.json -t ndjson > bc.concepts.ndjson

